const fs = require('node:fs/promises');
const path = require('node:path');

function pdfEscape(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function makePdf(lines) {
  const content = [
    'BT',
    '/F1 18 Tf',
    '72 760 Td',
    `(${pdfEscape(lines[0])}) Tj`,
    '/F1 11 Tf',
    ...lines.slice(1).flatMap((line) => ['0 -22 Td', `(${pdfEscape(line)}) Tj`]),
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}\nendstream`,
  ];

  let body = '%PDF-1.4\n';
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(body, 'utf8'));
    body += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xrefOffset = Buffer.byteLength(body, 'utf8');
  body += `xref\n0 ${objects.length + 1}\n`;
  body += '0000000000 65535 f \n';
  for (let index = 1; index < offsets.length; index += 1) {
    body += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return body;
}

async function writeInvoicePdf(filePath, invoice) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const lines = [
    'Wutong Agent Invoice',
    `Invoice No: ${invoice.invoiceNo}`,
    `Task ID: ${invoice.taskId}`,
    `Store Group: ${invoice.storeGroup}`,
    `Customer: ${invoice.customerName}`,
    `Amount: ${invoice.currency} ${invoice.amount}`,
    `Generated At: ${new Date().toISOString()}`,
    'Generated by Hermes Runtime POC after explicit user confirmation.',
  ];
  await fs.writeFile(filePath, makePdf(lines), 'binary');
}

module.exports = {
  writeInvoicePdf,
};
